global:
  scrape_interval: 20s
  scrape_timeout: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: be_checkin
  honor_timestamps: true
  scrape_interval: 20s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - task_ui:8080